### ISSUE TITLE
禁言时间显示异常

### ISSUE THREAD

**Issue by htxzdfunny** [MeowCatZ/alice-bot-cs-ce#26]
RT 如图所示
![image](https://user-images.githubusercontent.com/54425771/127994856-8590b25c-f699-4b74-b7f4-33f1d74efffb.png)
哈人 什么时候修一修

**Comment by MashiroSA** [comment]
新repo:https://github.com/ShizukuWorld/alice-bot-cs-sw
该项目repo将被废弃
